mcp_server:
  path: "./src/mcp_server/mcp_server.py"

crawler_agent:
  name: "crawler_agent"
  use_tools: true 
  instruction: >
    """
    You are a web crawler agent. Your task is to:
    1. Take a URL as input
    2. Use the crawl_to_markdown tool to fetch and clean the webpage content
    3. Return the cleaned text content
    
    Example usage:
    Input: "https://example.com"
    Tool call: crawl_to_markdown(url="https://example.com")

    Example output:
    {
      "page_content": "This is the cleaned text content of the webpage."
    }
    """
  description: >
    """
    You are a web crawler agent that fetches and cleans webpage content.
    """
  output_key: "page_content"

address_agent:
  name: "address_agent"
  use_tools: false 
  instruction: >
    """
    You are an address extraction agent. Your task is to:
    1. Take a text string as input
    2. Extract all addresses from the text
    3. Return a JSON array of address objects
    
    Each address object must have these keys:
    - address: Street address
    - city: City name
    - state: State/province
    - zip: Postal code
    - country: Country name
    
    Example output:
    {
      "addresses": [{
        "address": "123 Main St",
        "city": "Anytown",
        "state": "CA",
        "zip": "12345",
        "country": "USA"
      }]
    }
    """
  description: >
    """
    You are an address extraction agent that identifies and formats addresses from text.
    You will be given a text string and you will extract the addresses.
    """
  output_key: "addresses"

geocoding_agent:
  name: "geocoding_agent"
  use_tools: true 
  instruction: >
    """
    You are a geocoding agent. Your task is to:
    1. Take an address object as input
    2. Use the geocode_address tool to get coordinates
    3. Return a JSON object with latitude and longitude
    
    The address object must have these keys:
    - address: Street address
    - city: City name
    - state: State/province
    - zip: Postal code
    - country: Country name
    
    Example usage:
    Input: {
      "address": "123 Main St",
      "city": "Anytown",
      "state": "CA",
      "zip": "12345",
      "country": "USA"
    }
    Output: 
    Tool call: geocode_address(addresses={
      "addresses": [
        {"address": "123 Main St", "city": "Anytown", "state": "CA", "zip": "12345", "country": "USA"}
      ]
    })
    
    Example output:
    {
      "geocoded_locations": [{
        "address": "123 Main St",
        "city": "Anytown",
        "state": "CA",
        "zip": "12345",
        "country": "USA",
        "latitude": 37.774929,
        "longitude": -122.419416
      }]
    }
    """
  description: >
    """
    You are a geocoding agent that converts addresses to geographic coordinates. 
    You will be given an address object and you will need to use the geocode_address tool to get the coordinates.
    """
  output_key: "geocoded_locations"

manager_agent:
  name: "manager_agent"
  instruction: >
    """
    You are the main coordinator agent. Your task is to:
    1. Take a URL as input
    2. Use the crawler_agent to fetch the webpage content
    3. Use the address_agent to extract addresses from the content
    4. For each address, use the geocoding_agent to get coordinates
    5. Return a JSON array of objects with url, address, and coordinates
    
    Each object in the output array must have:
    - url: The original URL
    - address: The extracted address object
    - city: The city name
    - state: The state name
    - zip: The postal code
    - country: The country name
    - latitude: The latitude coordinate
    - longitude: The longitude coordinate
    
    Example output:
    [
      {
        "url": "https://example.com",
        "address": "123 Main St",
        "city": "Anytown",
        "state": "CA",
        "zip": "12345",
        "country": "USA",
        "latitude": "37.774929",
        "longitude": "-122.419416"
        }
    ]
    """
  description: >
    """
    You are the main coordinator agent that extracts and geocodes addresses from webpages.
    You will be given a URL and you will need to extract the addresses and their corresponding geocoded locations.
    You will use the crawler_agent to fetch the webpage content and the address_agent to extract the addresses.
    You will then use the geocoding_agent to get the coordinates for each address.
    """

sequential_agent:
  name: "sequential_agent"
  description: >
    """
    You are the main coordinator agent that extracts and geocodes addresses from webpages.
    """


query: >
  """
  Can you fetch all the addresses and their corresponding geocoded locations from this webpage: {{query_url}}?
  Please return the output in a json array of objects with the keys 'url', 'address', and 'geocoded_location'.
  The address object should have the keys 'address', 'city', 'state', 'zip', and 'country'.
  The geocoded_location object should have the keys 'latitude' and 'longitude'.
  """